### ISSUE TITLE
SIGKILL error on control_menu config

### ISSUE THREAD

**Issue by KorigamiK** [ahrm/sioyek#1274]
Here's my entire config:
`keys_user.config`

```sh
[m]control_menu('down') <C-n>
[m]control_menu('up') <C-p>
```

The app starts but if I try to press Ctrl+n/p I experience this crash

Command output
```sh
default_config_path: /etc/sioyek/prefs.config
default_keys_path: /etc/sioyek/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/origami/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/origami/.config/sioyek/keys_user.config
database_file_path: /home/origami/.local/share/sioyek/test.db
local_database_file_path: /home/origami/.local/share/sioyek/local.db
global_database_file_path: /home/origami/.local/share/sioyek/shared.db
tutorial_path: /usr/share/sioyek/tutorial.pdf
last_opened_file_address_path: /home/origami/.local/share/sioyek/last_document_path.txt
shader_path: /usr/share/sioyek/shaders
SIOYEK
warning: found duplicate fz_icc_link in the store
warning: found duplicate fz_icc_link in the store
[1]    10686 illegal hardware instruction (core dumped)  /home/origami/Dev/projects/cpp/sioyek/build/sioyek
```

GDB shows this when the error happens
```sh
Thread 1 "sioyek" received signal SIGILL, Illegal instruction.
MacroCommand::requires_document (this=0x555557cf4180) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/input.cpp:537
537	        if (is_modal) {
```

**Comment by KorigamiK** [comment]
happens on the latest development build

**Comment by ahrm** [comment]
Can't reproduce the issue. In what context do you press `<C-n` (e.g. is a particular menu open?)? Can you report the full gdb backtrace (`bt`).

**Comment by KorigamiK** [comment]
> Can't reproduce the issue. In what context do you press `<C-n` (e.g. is a particular menu open?)? Can you report the full gdb backtrace (`bt`).

Yeah, here's the backtrace:

```sh
#0  MacroCommand::requires_document (this=0x555557be2b80) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/input.cpp:537
#1  0x000055555575bd1a in Command::run (this=0x555557be2b80) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/input.cpp:7643
#2  0x00005555558c8d7a in MainWidget::advance_command (this=0x5555567bfeb0, new_command=std::unique_ptr<Command> = {...}, result=0x0) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/main_widget.cpp:5354
#3  0x00005555558c8c17 in MainWidget::handle_command_types (this=0x5555567bfeb0, new_command=std::unique_ptr<Command> = {...}, num_repeats=0, result=0x0) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/main_widget.cpp:2061
#4  0x00005555558c5697 in MainWidget::key_event (this=0x5555567bfeb0, released=false, kevent=0x7fffffffc1b0, is_auto_repeat=false) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/main_widget.cpp:2182
#5  0x00005555558c4928 in MainWidget::keyPressEvent (this=0x5555567bfeb0, kevent=0x7fffffffc1b0) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/main_widget.cpp:1605
#6  0x00007ffff354f42c in QWidget::event(QEvent*) () at /usr/lib/libQt6Widgets.so.6
#7  0x00005555558ecde7 in MainWidget::event (this=0x5555567bfeb0, event=0x7fffffffc1b0) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/main_widget.cpp:6496
#8  0x00007ffff34fe78a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#9  0x00007ffff3502ce2 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#10 0x00007ffff2557ac8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#11 0x00007ffff356ae06 in ??? () at /usr/lib/libQt6Widgets.so.6
#12 0x00007ffff34fe78a in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt6Widgets.so.6
#13 0x00007ffff2557ac8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt6Core.so.6
#14 0x00007ffff2b88b4c in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () at /usr/lib/libQt6Gui.so.6
#15 0x00007ffff2c02b44 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Gui.so.6
#16 0x00007ffff304ea14 in ??? () at /usr/lib/libQt6Gui.so.6
#17 0x00007ffff0dcc559 in ??? () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff0e2f257 in ??? () at /usr/lib/libglib-2.0.so.0
#19 0x00007ffff0dcba55 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff27c22fd in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#21 0x00007ffff2561ee6 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#22 0x00007ffff2558f4f in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#23 0x00005555558b1e5a in main (argc=1, args=0x7fffffffd238) at /home/origami/Dev/projects/cpp/sioyek/pdf_viewer/main.cpp:904
```

**Comment by ahrm** [comment]
In what context do you press <C-n (e.g. is a particular menu open?)?

**Comment by KorigamiK** [comment]
I just open sioyek normally and press <C-n> in the already open pdf, nothing else

**Comment by KorigamiK** [comment]
This PR fixes this but I'm not sure of the exact error of why this would happen in the first place:
https://github.com/ahrm/sioyek/pull/1275
