### ISSUE TITLE
[BUG REPORT ] + [ SUGGESTION ] Extensions don't work on macOS

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#512]
I found the extensions you have created for sioyek and I followed the instructions to install them. But unfortunately none of them work. I tried testing them outside of the program. Python finds `sioyek` and asks for arguments (name of the file). 

I think it would be beneficial to incorporate those extensions into the program. For example, the dual_panel feature is quite useful.

**Comment by ahrm** [comment]
I think the `%{sioyek_path}` does not correctly expand in macos. you have to manually replace it with the path of sioyek executable which is inside the `sioyek.app` package.

**Comment by ibehnam** [comment]
I tried `%{sioyek_path}` in terminal and got: `fg: job not found`. [Apparently](https://stackoverflow.com/questions/32614648/weird-jobs-behavior-within-zsh), it's an issue with zsh. I added an alias in my `zshrc` like so:

```
alias %{sioyek_path}="/Applications/sioyek.app/Contents/MacOS/sioyek"
```

But the extensions still won't work.

**Comment by ahrm** [comment]
No I meant manually replace "%{sioyek_path}" in `prefs_user.config` with the actual path.

**Comment by ibehnam** [comment]
Ok I did that but it's still not working:

```
new_command _download_paper python -m sioyek.paper_downloader download "/Applications/sioyek.app/Contents/MacOS/sioyek" "%{paper_name}"
control_click_command _download_paper

new_command _dual_panelify python -m sioyek.dual_panelify "/Applications/sioyek.app/Contents/MacOS/sioyek" "%{file_path}" "%{command_text}"

new_command _embed_annotations python -m sioyek.embed_annotations "/Applications/sioyek.app/Contents/MacOS/sioyek" "%{local_database}" "%{shared_database}" "%{file_path}"

new_command _extract_highlights python -m sioyek.extract_highlights "/Applications/sioyek.app/Contents/MacOS/sioyek" "%{local_database}" "%{shared_database}" "%1" %{zoom_level}

new_command _translate_selected_text python -m sioyek.translate "/Applications/sioyek.app/Contents/MacOS/sioyek" "%{selected_text}"
new_command _translate_current_line_text python -m sioyek.translate "/Applications/sioyek.app/Contents/MacOS/sioyek" "%{line_text}"
```

Is there something I'm missing?

**Comment by ahrm** [comment]
If you run something like this:
```
 python -m sioyek.embed_annotations "/Applications/sioyek.app/Contents/MacOS/sioyek" "%{local_database}" "%{shared_database}" "%{file_path}"
```
After replacing the `%{}` variables with the correct values on a command line, are there errors?

**Comment by ibehnam** [comment]
The `%{}` vars all give errors like this:

```
fg:fg:4: no current job
```

**Comment by ibehnam** [comment]
In case it helps:

I tried running the whole command on a PDF file from inside terminal:

```
>> python -m sioyek.embed_annotations "/Applications/sioyek.app/Contents/MacOS/sioyek" "%{local_database}" "%{shared_database}" "~/sample.pdf"
Traceback (most recent call last):
  File "/Users/<me>/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/<me>/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/<me>/opt/anaconda3/lib/python3.9/site-packages/sioyek/embed_annotations.py", line 40, in <module>
    document.embed_new_annotations(save=True, colormap=colormap)
  File "/Users/<me>/opt/anaconda3/lib/python3.9/site-packages/sioyek/sioyek.py", line 692, in embed_new_annotations
    self.embed_new_bookmarks()
  File "/Users/<me>/opt/anaconda3/lib/python3.9/site-packages/sioyek/sioyek.py", line 682, in embed_new_bookmarks
    new_bookmarks = self.get_non_embedded_bookmarks()
  File "/Users/<me>/opt/anaconda3/lib/python3.9/site-packages/sioyek/sioyek.py", line 720, in get_non_embedded_bookmarks
    candidate_bookmarks = self.get_bookmarks()
  File "/Users/<me>/opt/anaconda3/lib/python3.9/site-packages/sioyek/sioyek.py", line 855, in get_bookmarks
    doc_hash = self.get_hash()
  File "/Users/<me>/opt/anaconda3/lib/python3.9/site-packages/sioyek/sioyek.py", line 847, in get_hash
    path_hash_map = self.sioyek.get_path_hash_map()
  File "/Users/<me>/opt/anaconda3/lib/python3.9/site-packages/sioyek/sioyek.py", line 113, in get_path_hash_map
    cursor = self.get_local_database().execute(query)
sqlite3.OperationalError: no such table: document_hash
——————————————————————————————————————————————————

```

**Comment by ahrm** [comment]
You need to replace `%{local_database}` and `%{shared_database}` with the path of `local.db` and `shared.db` files which are located inside sioyek.app.

**Comment by ibehnam** [comment]
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/58621210/205362245-1a85b523-e8fd-461b-8cd9-00d59493003e.png">

Thanks for replying. I think the problem is that `local.db` and `shared.db` don't exist inside sioyek.app directory.

**Comment by ahrm** [comment]
Hmmm, when you execute sioyek from command line using the sioyek executable inside the app, it should print the path of its database files.

**Comment by ibehnam** [comment]
Thanks, now it prints the following:
```
default_config_path: /Applications/sioyek.app/Contents/MacOS/prefs.config
default_keys_path: /Applications/sioyek.app/Contents/MacOS/keys.config
user_config_path: [ 0 ] /Users/behnam/.config/sioyek/prefs_user.config
user_config_path: [ 1 ] /Users/behnam/Library/Application Support/sioyek/prefs_user.config
user_keys_path: [ 0 ] /Users/behnam/.config/sioyek/keys_user.config
user_keys_path: [ 1 ] /Users/behnam/Library/Application Support/sioyek/keys_user.config
database_file_path: /Users/behnam/Library/Application Support/sioyek/test.db
**local_database_file_path: /Users/behnam/Library/Application Support/sioyek/local.db
global_database_file_path: /Users/behnam/Library/Application Support/sioyek/shared.db**
tutorial_path: /Applications/sioyek.app/Contents/MacOS/tutorial.pdf
last_opened_file_address_path: /Users/behnam/Library/Application Support/sioyek/last_document_path.txt
shader_path: /Applications/sioyek.app/Contents/MacOS/shaders
Error: smooth_scroll_speed is not a valid configuration name
Error: smooth_scroll_drag is not a valid configuration name
Creating shared memory block...
Shared memory already exists: this is a secondary application.
Secondary application attaching to shared memory block...
Secondary application successfully attached to shared memory block.
Secondary application sent message to IPC server.
```
I replaced them but still no plugins work.

**Comment by ahrm** [comment]
When you replace them and *run it from command line* are there any errors?

**Comment by ibehnam** [comment]
I tried the following:

```
>>python -m sioyek.embed_annotations "/Applications/sioyek.app/Contents/MacOS/sioyek" "/Users/<user>/Library/Application Support/sioyek/local.db" "/Users/<user>/Library/Application Support/sioyek/shared.db" "/Users/<user>/Library/CloudStorage/sample.pdf"
```
and received this message:
```
default_config_path: /Applications/sioyek.app/Contents/MacOS/prefs.config
default_keys_path: /Applications/sioyek.app/Contents/MacOS/keys.config
user_config_path: [ 0 ] /Users/<user>/.config/sioyek/prefs_user.config
user_config_path: [ 1 ] /Users/<user>/Library/Application Support/sioyek/prefs_user.config
user_keys_path: [ 0 ] /Users/<user>/.config/sioyek/keys_user.config
user_keys_path: [ 1 ] /Users/<user>/Library/Application Support/sioyek/keys_user.config
database_file_path: /Users/<user>/Library/Application Support/sioyek/test.db
local_database_file_path: /Users/<user>/Library/Application Support/sioyek/local.db
global_database_file_path: /Users/<user>/Library/Application Support/sioyek/shared.db
tutorial_path: /Applications/sioyek.app/Contents/MacOS/tutorial.pdf
last_opened_file_address_path: /Users/<user>/Library/Application Support/sioyek/last_document_path.txt
shader_path: /Applications/sioyek.app/Contents/MacOS/shaders
Creating shared memory block...
Shared memory already exists: this is a secondary application.
Secondary application attaching to shared memory block...
Secondary application successfully attached to shared memory block.
Secondary application sent message to IPC server.
```

**Comment by ahrm** [comment]
It seems to be working. Are the annotations not embedded in the file?
