### ISSUE TITLE
Bug report: it can't run on the mac os 14

### ISSUE THREAD

**Issue by zerone0x** [ahrm/sioyek#903]
The dual_panelify is very useful in the common reading, but it looks there are some method changes on the script, it didn't work now.
`python3 dual_panelify.py "/Applications/sioyek.app/Contents/MacOS/sioyek"  "/Users/xx/Downloads/test.pdf"
Traceback (most recent call last):
  File "/Users/xx/Downloads/sioyek/scripts/dual_panelify.py", line 87, in <module>
    for i in range(pdf_reader.numPages // 2):
  File "/usr/local/anaconda3/lib/python3.10/site-packages/PyPDF2/_reader.py", line 467, in numPages
    deprecation_with_replacement("reader.numPages", "len(reader.pages)", "3.0.0")
  File "/usr/local/anaconda3/lib/python3.10/site-packages/PyPDF2/_utils.py", line 369, in deprecation_with_replacement
    deprecation(DEPR_MSG_HAPPENED.format(old_name, removed_in, new_name))
  File "/usr/local/anaconda3/lib/python3.10/site-packages/PyPDF2/_utils.py", line 351, in deprecation
    raise DeprecationError(msg)
PyPDF2.errors.DeprecationError: reader.numPages is deprecated and was removed in PyPDF2 3.0.0. Use len(reader.pages) instead.`

**Comment by jinjiaodawang** [comment]
It seems you are running the python script from the script dir, which contains a legacy version of ahrm/sioyek-python-extensions. Please follow the instructions from the ahrm/sioyek-python-extensions repository, install, and run the new version.
